# Generated by Django 5.1.1 on 2024-10-11 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0002_alter_apartamento_vagas_estacionamento'),
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apartamentos.apartamento', verbose_name='Apartamento'),
        ),
    ]
