# Generated by Django 5.1.1 on 2024-10-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0002_alter_morador_apartamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='cpf',
            field=models.CharField(default=77777777777, max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
