# Generated by Django 5.1.1 on 2024-10-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apartamento', models.CharField(max_length=5, verbose_name='Numero do apartamento')),
                ('bloco_apartamento', models.CharField(max_length=3, verbose_name='Bloco do apartamento')),
                ('vagas_estacionamento', models.CharField(max_length=4, verbose_name='Quantidade de vagas no estacionamento')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
                'db_table': 'apartamento',
            },
        ),
    ]
