# Generated by Django 5.1.1 on 2024-10-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo do morador')),
                ('contato', models.CharField(max_length=11, verbose_name='Contato do morador ')),
                ('apartamento', models.CharField(max_length=10, verbose_name='Apartamento do morador')),
            ],
            options={
                'verbose_name': 'Morador',
                'verbose_name_plural': 'Moradores',
                'db_table': 'morador',
            },
        ),
    ]
